org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47.4,)
loader_version_range=[47,)
mod_id=statues20
mod_name=Statues20
mod_license=GPL-2.0-only
mod_version=0.4.0
mod_group_id=che.statues20
mod_authors=Ché
mod_description=A deep Forge 1.20.1 recreation of the classic Statues sculpting mod, including pose sculpting, materialized player statues, equipment and showcases.
